# _config.yml
title: Benoit BARRAU | Gameplay Programmer
description: "Site statique déployé sur GitHub Pages avec Jekyll"
theme: null           # on n’utilise aucun thème préinstallé
markdown: kramdown
permalink: pretty     # URLs « propres » (sans .html)
